### ISSUE TITLE
For basic install, generate all dependencies from the operator

### ISSUE THREAD

**Issue by acmenezes** [Kong/gateway-operator#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

While testing the operator following the repo's instructions it failed requesting a secret possibly for certificates. Ideally for a certified operator the custom resource should be the only point of contact for an end user. I'm not sure if I missed something. I'm curious about that. Currently tested on OCP 4.10. And I actually saw certificate generation code and secret permissions as well on the project. So not sure if that proceeds.

### Proposed Solution

Generate any dependencies needed on behalf of the user.

### Acceptance Criteria

- [ ] Install operator and be able to create custom resources without any extra steps

**Comment by rainest** [comment]
@acmenezes do you have the errors in question available? I ran through the setup instructions in [log.txt](https://github.com/Kong/gateway-operator/files/9366632/log.txt) and didn't see any issues, and the certificates are configured on both sides, so we'd see failures if they weren't actually mounted:

```
16:47:02-0700 esenin $ kubectl describe po dataplane-kong-k4bx6-n6fdg-9ff985868-jv442 | grep NGINX_ADMIN
      KONG_NGINX_ADMIN_SSL_CLIENT_CERTIFICATE:  /var/cluster-certificate/ca.crt
      KONG_NGINX_ADMIN_SSL_VERIFY_CLIENT:       on
      KONG_NGINX_ADMIN_SSL_VERIFY_DEPTH:        3
16:47:07-0700 esenin $ kubectl describe po controlplane-kong-b8v7s-lqb77-55797765c-2ldpl | grep TLS_CLIENT
      CONTROLLER_KONG_ADMIN_TLS_CLIENT_CERT_FILE:  /var/cluster-certificate/tls.crt
      CONTROLLER_KONG_ADMIN_TLS_CLIENT_KEY_FILE:   /var/cluster-certificate/tls.key
```

The timing aligns with https://github.com/Kong/gateway-operator/pull/149 and the fix in https://github.com/Kong/gateway-operator/pull/162, but I don't think those should have caused issues: the new namespace flag isn't set by default or in tests, and the change includes logic to [fall back to using the Deployment namespace when it's unset](https://github.com/Kong/gateway-operator/pull/149/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R59-R69), which is what the tests are using (we didn't set the namespace explicitly in integration tests and instead set `POD_NAMESPACE` manually). Lacking the fix should have only caused issues if you were running the operator outside a cluster AFAICT.

It's possible there's some permissions reason that the operator cannot interact with the Secrets, but I'd expect that to raise an error earlier when creating the role, when running

```
kubectl kustomize https://github.com/kong/gateway-operator/config/default | kubectl apply -f -
```

**Comment by acmenezes** [comment]
Hi @rainest , thanks for checking on that. What cluster/version you're using. Here is what I get when trying to install the operator in OpenShift 4.10.26. It's a single node OpenShift just as note. Not sure if there are hard requirements on multi-nodes. But it gets stuck on container creating with the operator pod. Check the events section on the bottom.

```
oc get pods -n kong-system
NAME                                                  READY   STATUS              RESTARTS   AGE
gateway-operator-controller-manager-ddc879b87-tr28s   0/2     ContainerCreating   0          4m22s
```
and

```
oc describe pods gateway-operator-controller-manager-ddc879b87-tr28s -n  kong-system
Name:           gateway-operator-controller-manager-ddc879b87-tr28s
Namespace:      kong-system
Priority:       0
Node:           ip-10-0-5-114.us-west-2.compute.internal/10.0.5.114
Start Time:     Thu, 18 Aug 2022 16:09:00 -0400
Labels:         control-plane=controller-manager
                pod-template-hash=ddc879b87
Annotations:    kubectl.kubernetes.io/default-container: manager
                openshift.io/scc: restricted
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/gateway-operator-controller-manager-ddc879b87
Containers:
  manager:
    Container ID:  
    Image:         ghcr.io/kong/gateway-operator:main
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /manager
    Args:
      --health-probe-bind-address=:8081
      --metrics-bind-address=127.0.0.1:8080
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  128Mi
    Requests:
      cpu:      10m
      memory:   64Mi
    Liveness:   http-get http://:8081/healthz delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:  http-get http://:8081/readyz delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAMESPACE:  kong-system (v1:metadata.namespace)
    Mounts:
      /tmp/k8s-webhook-server/serving-certs from webhook-certificates (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vf8pw (ro)
  kube-rbac-proxy:
    Container ID:  
    Image:         gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
    Image ID:      
    Port:          8443/TCP
    Host Port:     0/TCP
    Args:
      --secure-listen-address=0.0.0.0:8443
      --upstream=http://127.0.0.1:8080/
      --logtostderr=true
      --v=0
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  128Mi
    Requests:
      cpu:        5m
      memory:     64Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vf8pw (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  webhook-certificates:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  gateway-operator-webhook-certs
    Optional:    false
  kube-api-access-vf8pw:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
    ConfigMapName:           openshift-service-ca.crt
    ConfigMapOptional:       <nil>
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    4m52s                 default-scheduler  Successfully assigned kong-system/gateway-operator-controller-manager-ddc879b87-tr28s to ip-10-0-5-114.us-west-2.compute.internal
  Warning  FailedMount  42s (x10 over 4m51s)  kubelet            MountVolume.SetUp failed for volume "webhook-certificates" : secret "gateway-operator-webhook-certs" not found
  Warning  FailedMount  32s (x2 over 2m49s)   kubelet            Unable to attach or mount volumes: unmounted volumes=[webhook-certificates], unattached volumes=[webhook-certificates kube-api-access-vf8pw]: timed out waiting for the condition
```

**Comment by rainest** [comment]
Did this Job fail to create or run with errors? It's what should create it:

```
15:00:29-0700 esenin $ kubectl logs -n kong-system jobs/gateway-operator-admission
W0818 22:00:31.462072       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"err":"secrets \"gateway-operator-webhook-certs\" not found","level":"info","msg":"no secret found","source":"k8s/k8s.go:229","time":"2022-08-18T22:00:31Z"}
{"level":"info","msg":"creating new secret","source":"cmd/create.go:28","time":"2022-08-18T22:00:31Z"}
```

```
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    name: gateway-operator-webhook
  name: gateway-operator-admission
  namespace: kong-system
spec:
  template:
    metadata:
      labels:
        name: gateway-operator-webhook
      name: admission-create
    spec:
      containers:
      - args:
        - create
        - --host=gateway-operator-validating-webhook,gateway-operator-validating-webhook.kong-system.svc
        - --namespace=kong-system
        - --secret-name=gateway-operator-webhook-certs
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
        imagePullPolicy: IfNotPresent
        name: create
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccountName: gateway-operator-admission
```
