### ISSUE TITLE
env of deployment for dataplane could not be set when dataplane has env

### ISSUE THREAD

**Issue by randmonkey** [Kong/gateway-operator#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Similar to #63, The default env could not be set if dataplane has set `spec.deploymentoptions.env`. Kong uses `postgres` as its default database, so this will make Kong fail to start if env is set in `spec.deploymentoptions.env` , but `KONG_DATABASE` not set.

### Expected Behavior

When I specify env in dataplane, the default envs are still set.

### Steps To Reproduce

Similar to #63, create a dataplane like this:
```
apiVersion: gateway-operator.konghq.com/v1alpha1
kind: DataPlane
metadata:
  creationTimestamp: "2022-08-29T09:47:14Z"
  generation: 1
  name: dp1
spec:
  env:
  - name: TEST_ENV
    value: before_update

```
The default envs  are not set, and the deployment could not be started, because `KONG_DATABASE` is not set,.
