### ISSUE TITLE
Providing image version in GatewayConfiguration without containerImage doesn't work

### ISSUE THREAD

**Issue by shaneutt** [Kong/gateway-operator#248]
### Current Behavior

Currently if you deploy the following:

```yaml
kind: GatewayConfiguration
apiVersion: gateway-operator.konghq.com/v1alpha1
metadata:
  name: kong
  namespace: default
spec:
  dataPlaneDeploymentOptions:
    containerImage: kong/kong
    version: 2.7.0
---
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: kong
spec:
  controllerName: konghq.com/gateway-operator
  parametersRef:
    group: gateway-operator.konghq.com
    kind: GatewayConfiguration
    name: kong
    namespace: default
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: kong
  namespace: default
spec:
  gatewayClassName: kong
  listeners:
  - name: http
    protocol: HTTP
    port: 80
```

This works and results in a `Deployment` for a `DataPlane` deployed with the correct image: `kong/kong:2.7.0`.

However, if you don't provide the image:

```yaml
kind: GatewayConfiguration
apiVersion: gateway-operator.konghq.com/v1alpha1
metadata:
  name: kong
  namespace: default
spec:
  dataPlaneDeploymentOptions:
    version: 2.7.0
---
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: kong
spec:
  controllerName: konghq.com/gateway-operator
  parametersRef:
    group: gateway-operator.konghq.com
    kind: GatewayConfiguration
    name: kong
    namespace: default
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: kong
  namespace: default
spec:
  gatewayClassName: kong
  listeners:
  - name: http
    protocol: HTTP
    port: 80
```

Then the version will be ignored and the default version will be used instead.

### Expected Behavior

When `version` is provided for a component, even if `containerImage` is _not_ the version should be applied to the default image.

### Steps To Reproduce

1. `ktf env create --addon metallb`
2. `kubectl kustomize https://github.com/Kong/kubernetes-ingress-controller/config/crd | kubectl apply -f -`
3. `kubectl kustomize https://github.com/kubernetes-sigs/gateway-api/config/crd | kubectl apply -f -`
4. `kubectl kustomize https://github.com/kong/gateway-operator/config/default | kubectl apply -f -`
5. `kubectl -n kong-system wait --for=condition=Available=true --timeout=120s deployment/gateway-operator-controller-manager`
6. `kubectl apply -f <yaml provided above>.yaml`
7. `kubectl get pod <pod> -o yaml | grep image`

### Kong Gateway Operator version

24ecefc85db7e0bfffbced38c76d74ebedc6885b

### Kubernetes version

```shell
1.22.0
```

### Additional Notes

We should ensure we make this work properly for both `DataPlane`  _and_ `ControlPlane`, though the examples only demonstrated `DataPlane`.
