### ISSUE TITLE
Manual upgrades not working with GatewayConfiguration

### ISSUE THREAD

**Issue by shaneutt** [Kong/gateway-operator#249]
### Current Behavior

When defining a custom `containerImage` and `version` for the `dataplaneDeploymentOptions`, if I update the `version` to a later version the upgrade is never triggered and the older version `Pod` remains.

### Expected Behavior

When upgrading the `version` the `Deployment` should be updated accordingly.

### Steps To Reproduce

Deploy with gateway 2.7.0:

```yaml
kind: GatewayConfiguration
apiVersion: gateway-operator.konghq.com/v1alpha1
metadata:
  name: kong
  namespace: default
spec:
  dataPlaneDeploymentOptions:
    containerImage: kong/kong
    version: 2.7.0
---
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: kong
spec:
  controllerName: konghq.com/gateway-operator
  parametersRef:
    group: gateway-operator.konghq.com
    kind: GatewayConfiguration
    name: kong
    namespace: default
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: kong
  namespace: default
spec:
  gatewayClassName: kong
  listeners:
  - name: http
    protocol: HTTP
    port: 80
```

Wait for the `Pod` to be full provisioned and the `Gateway` to be responding on it's `LoadBalancer` IP, and then use:

```console
kubectl edit gatewayconfigurations kong
```

To update the version to `2.8.0`.

The `Deployment` wont be upgraded.

### Kong Gateway Operator version

24ecefc85db7e0bfffbced38c76d74ebedc6885b

### Kubernetes version

```shell
v1.22.0
```

### Anything else?

We should ensure that this is fixed for both `DataPlane` _and_ `ControlPlane`.

It's worth noting, that the gateway controller _is updating the `DataPlane`_ when this happens, but the dataplane controller is not updating its `Deployment`.
