### ISSUE TITLE
Validating webhook is unreachable when running bundle on Open Shift

### ISSUE THREAD

**Issue by jrsmroz** [Kong/gateway-operator#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the gateway operator bundle is deployed on Open Shift cluster, the webhook connection is always unavailable.

### Expected Behavior

Webhook connection should succeed.

### Steps To Reproduce

```markdown
1. Deploy the operator bundle. The command that I used
$ operator-sdk run bundle -n jrsmroz ghcr.io/jrsmroz/kong-gateway-operator-bundle:v0.0.1

2. Wait.

3. Check the gateway status. It claims it failed calling  webhook.

$ k  describe -n jrsmroz gateway kong
# ... some omitted output ...
Status:
  Conditions:
    Last Transition Time:  2022-09-01T18:04:07Z
    Message:               There are other conditions that are not yet ready
    Reason:                DependenciesNotReady
    Status:                False
    Type:                  Ready
    Last Transition Time:  2022-09-01T18:04:07Z
    Message:               this gateway has been picked up by the konghq.com/gateway-operator and will be processed
    Reason:                Scheduled
    Status:                True
    Type:                  Scheduled
    Last Transition Time:  2022-09-01T18:04:07Z
    Message:               Internal error occurred: failed calling webhook "gateway-operator-validation.konghq.com": failed to call webhook: Post "https://gateway-operator-controller-manager-service.jrsmroz.svc:443/validate?timeout=5s": dial tcp 10.128.2.53:9443: connect: connection refused
    Reason:                UnableToProvision
    Status:                False
    Type:                  DataPlaneReady
Events:                    <none>

4. As a result the gateway does not receive the ip address, dataplane and controlplane are not created.
```

### Kong Gateway Operator version

```shell
ghcr.io/kong/gateway-operator@sha256:ccdc654fa852562365bea530ea6f7f9340cc7015c22c31023f517bef422869d3
```

### Kubernetes version

```shell
$ oc version
Client Version: 4.11.0
Kustomize Version: v4.5.4
Server Version: 4.10.26
Kubernetes Version: v1.23.5+012e945
```

**Comment by jrsmroz** [comment]
The secret was not created for some reason
```
k get secret -n jrsmroz gateway-operator-webhook-certs
```

**Comment by jrsmroz** [comment]
The jobs that creates the secret are for some reason not bundled. They're ignored.

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  namespace: kong-system
  name: admission
  # annotations:
  labels:
    name: gateway-operator-webhook
spec:
  template:
    metadata:
      name: admission-create
      labels:
        name: gateway-operator-webhook
    spec:
      containers:
        - name: create
          image: k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host=gateway-operator-validating-webhook,gateway-operator-validating-webhook.kong-system.svc
            - --namespace=kong-system
            - --secret-name=gateway-operator-webhook-certs
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: OnFailure
      serviceAccountName: gateway-operator-admission
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: kong-system
  name: admission-patch
  labels:
    name: gateway-operator-webhook
spec:
  template:
    metadata:
      name: admission-patch
      labels:
        name: gateway-operator-webhook
    spec:
      containers:
        - name: patch
          image: k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
          imagePullPolicy: IfNotPresent
          args:
            - patch
            - --webhook-name=gateway-operator-validation.konghq.com
            - --namespace=kong-system
            - --patch-mutating=false
            - --patch-validating=true
            - --secret-name=gateway-operator-webhook-certs
            - --patch-failure-policy=Fail
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: OnFailure
      serviceAccountName: gateway-operator-admission
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
```
